import { getRandomFloat } from "isaacscript-common";
import { Debugger } from "./debug";

/**
 * This function returns the luck bonus.
 *
 * @param luck Luck stat
 * @returns Calculated luck bonus.
 */
const luckBonus = (luck: number) => luck * 2;

/**
 * Generates a raw random roll percent value.
 *
 * This function returns a pseudo-random number in the range [0, 100).
 *
 * ### Notes
 *
 * uses `getRandomFloat(0, 100, rng)` internally.
 *
 * @returns A random number between 0 (inclusive) and 100 (exclusive).
 * @example
 * ```ts
 * const r = rollPercent();
 * if (r < 25) {
 *   // 25% chance
 * }
 * ```
 */
export const rollPercent = (rng: RNG): number => getRandomFloat(0, 100, rng);

/**
 * Computes the final probability chance after applying a Luck modifier.
 *
 * This function adjusts a base percentage using a Luck-based bonus and clamps the result between 0
 * and 100.
 *
 * Formula: `percent + luckBonus(luck)`
 *
 * @param percent Base success chance as a percentage (0–100).
 * @param luck Luck modifier. Defaults to 0.
 * @param allowNegative If `true` then luck defaults to 0 if it's a negative number.
 * @returns Final computed chance, clamped between 0 and 100.
 * @see {@link luckBonus} Helper method to return a constant luck bonus.
 * @example
 * ```ts
 * // 25% base chance, no luck
 * calcChance(25); // base chance (25%)
 * ```
 * @example
 * ```ts
 * // 25% base chance, positive luck
 * calcChance(25, 5); // increased chance (~32.5%)
 * ```
 * @example
 * ```ts
 * // 25% base chance, negative luck will default to 0
 * calcChance(25, -5, true); // base chance(17.5%)
 * ```
 */
export const calcChance = (
  percent: number,
  luck = 0,
  allowNegative = false,
  debug = false,
): number => {
  const bonus = luckBonus(allowNegative ? luck : Math.max(luck, 0));
  const finalChance = percent + bonus;
  const clampedChance = Math.max(0, Math.min(finalChance, 100));

  if (debug) {
    Debugger.rng(
      "calcChance",
      `Base percent: ${percent.toFixed(2)}%, Luck: ${luck.toFixed(2)}, Luck Bonus: ${bonus.toFixed(2)}, Chance: ${clampedChance.toFixed(2)}%`,
    );
  }

  return clampedChance;
};
/**
 * Resolves a single roll against multiple cumulative probability thresholds.
 *
 * This function takes a pre-generated roll value and a list of chances, and determines which index
 * the roll falls into based on cumulative probability.
 *
 * Each chance represents a percentage (0–100), and is evaluated in order.
 *
 * ### Notes
 * - Expects a roll value typically generated by {@link rollPercent}.
 * - Probabilities are evaluated cumulatively from left to right.
 * - Returns `-1` if the roll does not fall within any provided range.
 *
 * @param roll A pre-generated random value (0–100).
 * @param chances List of percentage chances (0–100).
 * @returns The index of the matched chance, or `-1` if none matched.
 * @example
 * ```ts
 * const r = rollPercent();
 * const result = rollFromChances(r, 20, 30);
 *
 * // 0 → first 20%
 * // 1 → next 30% (20–50)
 * // -1 → remaining 50%
 * ```
 * @example
 * ```ts
 * if (result === 0) {
 *   // first outcome
 * } else if (result === 1) {
 *   // second outcome
 * }
 * ```
 */

export const rollFromChances = (
  rng: RNG,
  ...chances: readonly number[]
): number => {
  let cumulative = 0;

  const roll = rollPercent(rng);
  for (const [i, chance] of chances.entries()) {
    cumulative += chance;
    if (roll < cumulative) {
      return i;
    }
  }

  return -1;
};

/**
 * Performs a probability roll using the given RNG.
 *
 * This is the standard helper for all chance-based logic. It is deterministic as long as the
 * provided RNG is deterministic.
 *
 * @param percent Base success chance (0–100).
 * @param rng RNG instance (e.g. from `npc.GetDropRNG()`).
 * @param luck Optional luck modifier.
 * @param debug `true` if chance calculations should print debug lines.
 * @returns `true` if the roll succeeds.
 * @example
 * ```ts
 * const rng = npc.GetDropRNG();
 * if (rollChance(25, rng)) {
 *   // 25% chance
 * }
 * ```
 * @example
 * ```ts
 * if (rollChance(25, rng, player.Luck)) {
 *   // luck-scaled chance
 * }
 * ```
 */
export const rollChance = (
  percent: number,
  rng: RNG,
  luck = 0,
  debug = false,
): boolean => {
  const chance = calcChance(percent, luck, true, debug);
  return rollPercent(rng) < chance;
};

/**
 * Rolls an item from a weighted list using a deterministic RNG system.
 *
 * This function first checks a global drop chance (optionally modified by luck). If the global roll
 * succeeds, it selects one item based on the relative weights provided. Items with higher weights
 * are more likely to be chosen.
 *
 * ### Notes
 * - Weights do **not** get affected by luck; they determine the relative probabilities among items.
 * - If all weights are 0 or negative, the function returns `undefined`.
 *
 * @template T The type of item to be selected.
 * @param items Array of items to select from.
 * @param weights Array of numeric weights corresponding to each item.
 * @param rng RNG instance to use for deterministic rolling.
 * @param chance Optional global chance (0–100%) to allow an item to drop. Defaults to 100.
 * @param luck Optional luck stat that **only modifies the global drop chance**, not item weights.
 * @returns Selected item or `undefined` if global roll fails or no weighted item is selectable.
 * @example
 * ```ts
 * const items = ["Red", "Blue", "Green"];
 * const weights = [5, 10, 1];
 * const selected = rollWeightedWithChance(items, weights, rng, player.Luck, 50);
 * ```
 */
export const rollWeighted = <T>(
  items: readonly T[],
  weights: readonly number[],
  rng: RNG,
  chance = 100,
  luck = 0,
): T | undefined => {
  // Roll against the global chance to determine if an item can drop.
  if (!rollChance(chance, rng, luck, true)) {
    Debugger.rng("rollWeighted", "Global chance failed");
    return undefined;
  }

  // Calculate total weight of all items.
  const totalWeight = weights.reduce((sum, w) => sum + w, 0);
  if (totalWeight <= 0) {
    Debugger.rng("rollWeighted", "Total weight is zero or negative");
    return undefined;
  }

  // Roll a random value between 0 and totalWeight.
  const roll = rng.RandomFloat() * totalWeight;
  Debugger.rng(
    "rollWeighted",
    `TotalWeight: ${totalWeight.toFixed(2)}, Roll: ${roll.toFixed(2)}, Items: ${items.length}`,
  );

  // Iterate through items and select the one where the roll falls in its cumulative weight range.
  let cumulative = 0;
  for (const [i, item] of items.entries()) {
    cumulative += weights[i] ?? 0;

    if (roll < cumulative) {
      Debugger.rng("rollWeighted", `Selected index: ${i}`);
      return item;
    }
  }

  // Fallback: return undefined if no item was selected
  Debugger.rng("rollWeighted", "No item selected from weights");
  return undefined;
};
