import { getRandomFloat } from "isaacscript-common";
import { Debugger } from "./debug";

/**
 * This function returns the luck bonus.
 *
 * @param luck Luck stat
 * @returns Calculated luck bonus.
 */
const luckBonus = (luck: number) => luck * 2;

/**
 * Generates a raw random roll percent value.
 *
 * This function returns a pseudo-random number in the range [0, 100).
 *
 * ### Notes
 *
 * uses `getRandomFloat(0, 100, rng)` internally.
 *
 * @returns A random number between 0 (inclusive) and 100 (exclusive).
 * @example
 * ```ts
 * const r = rollPercent();
 * if (r < 25) {
 *   // 25% chance
 * }
 * ```
 */
const getRandomPercent = (rng: RNG): number => getRandomFloat(0, 100, rng);

/**
 * Computes the final probability chance after applying a Luck modifier.
 *
 * This function adjusts a base percentage using a Luck-based bonus and clamps the result between 0
 * and 100.
 *
 * Formula: `percent + luckBonus(luck)`
 *
 * @param percent Base success chance as a percentage (0–100).
 * @param luck Luck modifier. Defaults to 0.
 * @param allowNegative If `true` then luck defaults to 0 if it's a negative number.
 * @returns Final computed chance, clamped between 0 and 100.
 * @see {@link luckBonus} Helper method to return a constant luck bonus.
 * @example
 * ```ts
 * // 25% base chance, no luck
 * calcChance(25); // base chance (25%)
 * ```
 * @example
 * ```ts
 * // 25% base chance, positive luck
 * calcChance(25, 5); // increased chance (~32.5%)
 * ```
 * @example
 * ```ts
 * // 25% base chance, negative luck
 * calcChance(25, -5, true); // base chance(17.5%)
 * ```
 */
export const calcChance = (
  percent: number,
  luck = 0,
  allowNegative = false,
): number => {
  const bonus = luckBonus(allowNegative ? luck : Math.max(luck, 0));
  const finalChance = percent + bonus;
  const clampedChance = Math.max(0, Math.min(finalChance, 100));

  Debugger.rng(
    "calcChance",
    `Base percent: ${percent.toFixed(2)}%, Luck: ${luck.toFixed(2)}, Luck Bonus: ${bonus.toFixed(2)}, Chance: ${clampedChance.toFixed(2)}%`,
  );

  return clampedChance;
};
/**
 * Resolves a single roll against multiple cumulative probability thresholds.
 *
 * This function takes a pre-generated roll value and a list of chances, and determines which index
 * the roll falls into based on cumulative probability.
 *
 * Each chance represents a percentage (0–100), and is evaluated in order.
 *
 * ### Notes
 * - Expects a roll value typically generated by {@link rollPercent}.
 * - Probabilities are evaluated cumulatively from left to right.
 * - Returns `-1` if the roll does not fall within any provided range.
 *
 * @param roll A pre-generated random value (0–100).
 * @param chances List of percentage chances (0–100).
 * @returns The index of the matched chance, or `-1` if none matched.
 * @example
 * ```ts
 * const r = rollPercent();
 * const result = rollFromChances(r, 20, 30);
 *
 * // 0 → first 20%
 * // 1 → next 30% (20–50)
 * // -1 → remaining 50%
 * ```
 * @example
 * ```ts
 * if (result === 0) {
 *   // first outcome
 * } else if (result === 1) {
 *   // second outcome
 * }
 * ```
 */

export const rollFromChances = (
  rng: RNG,
  ...chances: readonly number[]
): number => {
  let cumulative = 0;

  const roll = getRandomPercent(rng);
  for (const [i, chance] of chances.entries()) {
    cumulative += chance;
    if (roll < cumulative) {
      return i;
    }
  }

  return -1;
};

/**
 * Performs a probability roll using the given RNG.
 *
 * This is the standard helper for all chance-based logic. It is deterministic as long as the
 * provided RNG is deterministic.
 *
 * @param percent Base success chance (0–100).
 * @param rng RNG instance (e.g. from `npc.GetDropRNG()`).
 * @param luck Optional luck modifier.
 * @returns `true` if the roll succeeds.
 * @example
 * ```ts
 * const rng = npc.GetDropRNG();
 * if (rollChance(25, rng)) {
 *   // 25% chance
 * }
 * ```
 * @example
 * ```ts
 * if (rollChance(25, rng, player.Luck)) {
 *   // luck-scaled chance
 * }
 * ```
 */
export const rollChance = (percent: number, rng: RNG, luck = 0): boolean =>
  getRandomPercent(rng) < calcChance(percent, luck, true);

/**
 * Rolls an item from a weighted list using a deterministic RNG system.
 *
 * Works with:
 * - Fractional weights (0 < w < 1) are proportionally less likely.
 * - Negative weights are extremely rare but possible.
 * - Large weights scale proportionally.
 * - Optional global drop chance and luck.
 *
 * @template T The type of item to select.
 * @param items Array of items to select from.
 * @param weights Array of numeric weights corresponding to each item.
 * @param rng RNG instance to use for deterministic rolling.
 * @param chance Chance (0–100%) to allow an roll a weighted item. Defaults to 100.
 * @param luck Optional luck stat that modifies the global drop chance. Defaults to 0.
 * @returns Selected item or `undefined` if global roll fails or no weighted item is selectable. *
 *
 * ### Remarks
 * - **Testing rare weights**: Set the weight of an item to a very low value (e.g., 0.0001) and run
 *   multiple iterations (1000+) to verify it appears extremely rarely.
 * - **Verify RNG determinism**: Use the same RNG seed and rerun the roll; the selected item should
 *   always be the same, perfect for debugging.
 * - **Visual debugging**: Enable `debug = true` in `rollChance` if using it for global chance. The
 *   `Debugger.rng` logs show the roll, total weight, and chosen index.
 * - **Scaling weights**: For extremely large numbers, the ratio between items is what matters, not
 *   the absolute value. You can safely use 1, 10, 100, etc.
 */
export const rollWeighted = <T>(
  items: readonly T[],
  weights: readonly number[],
  rng: RNG,
  chance: number,
  luck = 0,
): T | undefined => {
  if (!rollChance(chance, rng, luck)) {
    Debugger.rng("rollWeighted", "Global chance failed");
    return undefined;
  }

  if (items.length === 0 || weights.length !== items.length) {
    Debugger.rng("rollWeighted", "Invalid items or weights");
    return undefined;
  }

  const safeWeights = weights.map((w) => (w <= 0 ? 0.0001 : w));
  const totalWeight = safeWeights.reduce((sum, w) => sum + w, 0);

  const roll = getRandomFloat(0, totalWeight, rng);
  Debugger.rng("rollWeighted", `TotalWeight: ${totalWeight}, Roll: ${roll}`);

  let cumulative = 0;
  for (const [i, item] of items.entries()) {
    cumulative += safeWeights[i] ?? 0;
    if (roll < cumulative) {
      Debugger.rng("rollWeighted", `Selected index: ${i}`);
      return item;
    }
  }

  Debugger.rng("rollWeighted", "No item selected from weights");
  return undefined;
};
