import { Debugger } from "./debug";

/**
 * This function returns the luck bonus.
 *
 * @param luck Luck stat
 * @returns Calculated luck bonus.
 */
const luckBonus = (luck: number) => luck * 2;

/**
 * Generates a raw random roll value for probability checks.
 *
 * This function returns a pseudo-random number in the range [0, 100), which can be reused across
 * multiple probability comparisons.
 *
 * ### Notes
 * - Uses `Math.random()`, which generates a pseudo-random number in the range [0, 1].
 *
 * @returns A random number between 0 (inclusive) and 100 (exclusive).
 * @example
 * ```ts
 * const r = rollValue();
 * if (r < 25) {
 *   // 25% chance
 * }
 * ```
 */
export const rollValue = (): number => Math.random() * 100;

/**
 * Computes the final probability chance after applying a Luck modifier.
 *
 * This function adjusts a base percentage using a Luck-based bonus and clamps the result between 0
 * and 100.
 *
 * Formula: `percent + luckBonus(luck)`
 *
 * @param percent Base success chance as a percentage (0–100).
 * @param luck Luck modifier. Defaults to 0.
 * @returns Final computed chance, clamped between 0 and 100.
 * @see {@link luckBonus} Helper method to return a constant luck bonus.
 * @example
 * ```ts
 * // 25% base chance, no luck
 * calcChance(25); // base chance (25%)
 * ```
 * @example
 * ```ts
 * // 25% base chance, positive luck
 * calcChance(25, 5); // increased chance (~32.5%)
 * ```
 * @example
 * ```ts
 * // 25% base chance, negative luck defaults to 0
 * calcChance(25, -5); // base chance(25%)
 * ```
 */
export const calcChance = (percent: number, luck = 0): number => {
  const bonus = luckBonus(Math.max(luck, 0));
  const finalChance = percent + bonus;
  const clampedChance = Math.max(0, Math.min(finalChance, 100));

  Debugger.rng(
    "calcChance",
    `Base percent: ${percent}, Luck: ${luck.toFixed(1)}, Luck Bonus: ${bonus.toFixed(1)}, Chance: ${clampedChance.toFixed(
      2,
    )}%`,
  );

  return clampedChance;
};

/**
 * Resolves a single roll against multiple cumulative probability thresholds.
 *
 * This function takes a pre-generated roll value and a list of chances, and determines which index
 * the roll falls into based on cumulative probability.
 *
 * Each chance represents a percentage (0–100), and is evaluated in order.
 *
 * ### Notes
 * - Expects a roll value typically generated by {@link rollValue}.
 * - Probabilities are evaluated cumulatively from left to right.
 * - Returns `-1` if the roll does not fall within any provided range.
 *
 * @param roll A pre-generated random value (0–100).
 * @param chances List of percentage chances (0–100).
 * @returns The index of the matched chance, or `-1` if none matched.
 * @example
 * ```ts
 * const r = rollValue();
 * const result = rollFromChances(r, 20, 30);
 *
 * // 0 → first 20%
 * // 1 → next 30% (20–50)
 * // -1 → remaining 50%
 * ```
 * @example
 * ```ts
 * if (result === 0) {
 *   // first outcome
 * } else if (result === 1) {
 *   // second outcome
 * }
 * ```
 */
// eslint-disable-next-line complete/prefer-readonly-parameter-types
export const rollFromChances = (roll: number, ...chances: number[]): number => {
  let cumulative = 0;

  for (const [i, chance] of chances.entries()) {
    cumulative += chance;
    if (roll < cumulative) {
      return i;
    }
  }

  return -1;
};

/**
 * Performs a probability roll influenced by a Luck modifier.
 *
 * This function evaluates a base percentage chance adjusted by a Luck-based bonus, then compares it
 * against a random roll.
 *
 * Formula: `calcChance(percent, luck)`
 *
 * The computed chance is clamped between 0 and 100 before being evaluated against a random roll in
 * the range [0, 100).
 *
 * @param percent Base success chance as a percentage (0–100).
 * @param luck Luck modifier. Defaults to 0.
 * @returns `true` if the roll succeeds, otherwise `false`.
 * @see {@link luckBonus} Helper method to return a constant luck bonus.
 * @see {@link calcChance} Computes the final clamped probability.
 * @example
 * ```ts
 * // 25% base chance, no luck
 * roll(25); // base success rate (25%)
 * ```
 * @example
 * ```ts
 * // 25% base chance, positive luck
 * roll(25, 5); // increased success rate (~32.5%)
 * ```
 * @example
 * ```ts
 * // 25% base chance, negative luck defaults to 0
 * roll(25, -5); // base success rate (25%)
 * ```
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const roll = (percent: number, luck = 0): boolean => {
  const clampedChance = calcChance(percent, luck);
  return rollValue() < clampedChance;
};
